### ISSUE TITLE
PSF stage does not work interactively with 64-bit IRAF

### ISSUE THREAD

**Issue by abostroem** [LCOGT/lcogtsnpipe#33]
The interactive option of the PSF stage does not work with 64-bit IRAF. 

This is an issue for anyone running the pipeline on Catalina and for the current docker file

This stage is recommended for creating the PSF for template images and is useful for troubleshooting a poor PSF (say one of your PSF stars is a close to another star - creating a double peaked PSF).

This is the error you get:
```
Killing IRAF task `psf'
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/site-packages/lsc/lscpsfdef.py", line 382, in ecpsf
  photmag, pst, fitmag = psffit(img, fwhm, psfstars, hdr, interactive, _datamin, _datamax, psffun, fixaperture)
 File "/usr/local/lib/python2.7/site-packages/lsc/lscpsfdef.py", line 208, in psffit
  verify=False, verbose=False)
 File "/usr/local/lib/python2.7/site-packages/pyraf/iraftask.py", line 767, in __call__
  return self.run(*args, **kw)
 File "/usr/local/lib/python2.7/site-packages/pyraf/iraftask.py", line 359, in run
  self._run(redirKW, specialKW)
 File "/usr/local/lib/python2.7/site-packages/pyraf/iraftask.py", line 811, in _run
  "\n"+str(value))
IrafError: Error running IRAF task psf
IRAF task terminated abnormally
ERROR (851, "Cannot restore graphics world coordinate systems")
```

If this is something we actually want to fix - these links might be useful (although I'll note the STScI trac links and the NOAO ftp link is broken)
* https://iraf.net/forum/viewtopic.php?showtopic=1469330
* https://github.com/iraf-community/iraf/issues/40

**Comment by abostroem** [comment]
We tried having the docker build a 32-bit machine with 32-bit IRAF but ran into issues with having the files stored outside IRAF on a 64 bit machine (the inode number was 64 bit). It appears this issue is not solvable without rewriting IRAF.
